### PR TITLE
REF: Add choices to to_distance parameter 

### PR DESCRIPTION
**Pull request by cherman2**

### CODE REVIEW

**Review by lizgehret — COMMENTED** [review]
this lgtm @cherman2 - only thought is maybe it would be good to add a couple of unit tests to assert this behavior change? i.e. raisesRegex for strings not 'baseline' or 'donor

**Comment by cherman2** [comment]
Yeah I definitely can do that. I thought about adding those but I wasn't sure if I should be testing it becuase its like qiime framework functionality?

**Comment by lizgehret** [comment]
For posterity - we discussed offline and don't need to add tests for this functionality since it is coming from the framework directly.

I'll test this locally @cherman2 and then it should be good to merge!

**Comment by lizgehret** [comment]
Screen Shot 2024-07-15 at 2 43 33 PM

Sadly this seems to work as expected and distance_to `ziggy` is not yet supported. Hopefully we'll see this in the future @cherman2 but in the meantime lgtm!

**Review by lizgehret — APPROVED** [review]

**Pull request merged**
