### PR TITLE
Reformat for new library spec

### PR DESCRIPTION
**Pull request by Oddant1**
Changes for the changed library spec.

### CODE REVIEW

**Comment by Oddant1** [comment]
Note, I changed the registration of q2-fmt in library-plugins to point to this branch on my remote for the time being. It will need to be updated when the changes are applied to the dev branch

**Comment by Oddant1** [comment]
@cherman2, @gregcaporaso, @ebolyen some or all of us should get together and make sure we are cool with the current state of things for an alpha release of library.

**Comment by cherman2** [comment]
Happy to meet. Is this something we should prioritize for the release?

**Review by cherman2 — APPROVED** [review]

**Comment by cherman2** [comment]
> Note, I changed the registration of q2-fmt in library-plugins to point to this branch on my remote for the time being. It will need to be updated when the changes are applied to the dev branch

Hi @Oddant1, Is there anything I need to do for this?

**Comment by Oddant1** [comment]
@cherman2 no

**Pull request merged**
